version: "3.8"
services:
    diov:
        build: .
        container_name: diov
        ports:
          - 5000:80
        environment:
            ConnectionStrings__Redis: redis
            ConnectionStrings__Sql: Server=mssql;Database=Diov;User ID=SA;Password=P@ssword123;
        entrypoint:
          - "/wait-for-it.sh"
          - "mssql:1433"
          - "-t"
          - "120"
          - "--"
          - "dotnet"
          - "/app/Diov.dll"
        depends_on:
          - mssql
          - redis
    mssql:
        image: mcr.microsoft.com/mssql/server:2019-latest
        container_name: mssql
        ports:
          - 1433:1433
        environment:
            ACCEPT_EULA: "Y"
            MSSQL_PID: "Express"
            SA_PASSWORD: "P@ssword123"
    redis:
        image: redis
        container_name: redis
        ports:
          - 6379:6379