apiVersion: v1
kind: Service
metadata:
    name: db
    labels:
        service: diov
spec:
    selector:
        service: diov
    ports:
      - port: 1433
---
apiVersion: v1
kind: Service
metadata:
    name: redis
    labels:
        service: diov
spec:
    selector:
        service: diov
    ports:
      - port: 6379
---
apiVersion: v1
kind: Service
metadata:
    name: web
    labels:
        service: diov
spec:
    selector:
        service: diov
    ports:
      - name: http
        port: 80