apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        {{- include "diov.db.labels" . | nindent 8 }}
    name: db
spec:
    replicas: {{ .Values.db.replicas }}
    strategy:
        type: Recreate
    selector:
        matchLabels:
            {{- include "diov.db.selectorLabels" . | nindent 12 }}
    template:
        metadata:
            labels:
                {{- include "diov.db.selectorLabels" . | nindent 16 }}
        spec:
            securityContext:
                runAsUser: 10001
                fsGroup: 0
            terminationGracePeriodSeconds: 10
            containers:
              - name: db
                image: {{ .Values.db.image | quote }}
                ports:
                  - name: db
                    containerPort: 1433
                env:
                  - name: MSSQL_PID
                    value: Developer
                  - name: ACCEPT_EULA
                    value: "Y"
                  - name: MSSQL_SA_PASSWORD
                    value: {{ .Values.db.saPassword | quote }}
                {{- if or .Values.db.persistence.enabled .Values.db.additionalVolumeMounts }}
                volumeMounts:
                  {{- if .Values.db.persistence.enabled }}
                  - name: db
                    mountPath: {{ .Values.db.persistence.mountPath | quote }}
                  {{- end }}
                  {{- with .Values.db.additionalVolumeMounts }}
                  {{- toYaml . | nindent 18 }}
                  {{- end }}
                {{- end }}
                resources: {{- toYaml .Values.db.resources | nindent 20 }}
            {{- if or .Values.db.persistence.enabled .Values.db.additionalVolumes }}
            volumes:
              {{- if .Values.db.persistence.enabled }}
              - name: db
                persistentVolumeClaim:
                    claimName: db
              {{- end }}
              {{- with .Values.db.additionalVolumes }}
              {{- toYaml . | nindent 14 }}
              {{- end }}
            {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        {{- include "diov.redis.labels" . | nindent 8 }}
    name: redis
spec:
    replicas: {{ .Values.redis.replicas }}
    strategy:
        type: Recreate
    selector:
        matchLabels:
            {{- include "diov.redis.selectorLabels" . | nindent 12 }}
    template:
        metadata:
            labels:
                {{- include "diov.redis.selectorLabels" . | nindent 16 }}
        spec:
            containers:
              - name: redis
                image: {{ .Values.redis.image | quote }}
                ports:
                  - containerPort: 6379
                {{- if or .Values.redis.persistence.enabled .Values.redis.additionalVolumeMounts }}
                volumeMounts:
                  {{- if .Values.redis.persistence.enabled }}
                  - mountPath: {{ .Values.redis.persistence.mountPath | quote }}
                    name: redis
                  {{- end }}
                  {{- with .Values.redis.additionalVolumeMounts }}
                  {{- toYaml . | nindent 18 }}
                  {{- end }}
                {{- end }}
                resources: {{- toYaml .Values.redis.resources | nindent 20 }}
            {{- if or .Values.redis.persistence.enabled .Values.redis.additionalVolumes }}
            volumes:
              {{- if .Values.redis.persistence.enabled }}
              - name: redis
                persistentVolumeClaim:
                    claimName: redis
              {{- end }}
              {{- with .Values.redis.additionalVolumes }}
              {{- toYaml . | nindent 14 }}
              {{- end }}
            {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        {{- include "diov.web.labels" . | nindent 8 }}
    name: web
spec:
    replicas: {{ .Values.web.replicas }}
    selector:
        matchLabels:
            {{- include "diov.web.selectorLabels" . | nindent 12 }}
    template:
        metadata:
            labels:
                {{- include "diov.web.selectorLabels" . | nindent 16 }}
        spec:
            containers:
              - image: {{ .Values.web.image | quote }}
                name: web
                ports:
                  - name: http
                    containerPort: 80
                    protocol: TCP
                env:
                  - name: ASPNETCORE_ENVIRONMENT
                    value: Production
                  - name: ConnectionStrings__Redis
                    value: redis
                  - name: ConnectionStrings__Sql
                    value: Server=db;Database=Diov;User Id={{ .Values.web.db.userId }};Password={{ .Values.web.db.password }};Encrypt=False;
                  - name: ExternalAuthentication__Google__AdminAuthorization
                    value: {{ .Values.web.externalIdentityProviders.google.adminAuthorization | quote }}
                  - name: ExternalAuthentication__Google__ClientId
                    value: {{ .Values.web.externalIdentityProviders.google.clientId | quote }}
                  - name: ExternalAuthentication__Google__ClientSecret
                    value: {{ .Values.web.externalIdentityProviders.google.clientSecret | quote }}
                  - name: Serilog__MinimumLevel
                    value: {{ .Values.web.serilog.minimumLevel | quote }}
                {{- if or .Values.web.persistence.enabled .Values.web.additionalVolumeMounts }}
                volumeMounts:
                  {{- if .Values.web.persistence.enabled }}
                  - name: web
                    mountPath: {{ .Values.web.persistence.mountPath | quote }}
                    readOnly: true
                  {{- end }}
                  {{- with .Values.web.additionalVolumeMounts }}
                  {{- toYaml . | nindent 18 }}
                  {{- end }}
                {{- end }}
                resources: {{- toYaml .Values.web.resources | nindent 20 }}
                livenessProbe:
                    httpGet:
                        path: /health/live
                        port: http
                    periodSeconds: 15
                    timeoutSeconds: 5
                readinessProbe:
                    httpGet:
                        path: /health/ready
                        port: http
                    periodSeconds: 60
                    timeoutSeconds: 15
                startupProbe:
                    httpGet:
                        path: /health/ready
                        port: http
                    failureThreshold: 10
                    periodSeconds: 5
            restartPolicy: Always
            {{- if or .Values.web.persistence.enabled .Values.web.additionalVolumes }}
            volumes:
              {{- if .Values.web.persistence.enabled }}
              - name: web
                persistentVolumeClaim:
                    claimName: web
              {{- end }}
              {{- with .Values.web.additionalVolumes }}
              {{- toYaml . | nindent 14 }}
              {{- end }}
            {{- end }}
