apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    annotations:
        {{- toYaml .Values.web.ingress.annotations | nindent 8 }}
    labels:
        {{- include "diov.web.labels" . | nindent 8 }}
    name: web
spec:
    {{- if .Values.web.ingress.className }}
    ingressClassName: {{ .Values.web.ingress.className }}
    {{- end }}
    tls:
      - hosts:
          - {{ .Values.web.host | quote }}
        secretName: tls
    rules:
      - host: {{ .Values.web.host | quote }}
        http:
            paths:
              - path: /
                pathType: Prefix
                backend:
                    service:
                        name: web
                        port:
                            number: 80