apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: db
spec:
    accessModes:
      - ReadWriteMany
    resources:
        requests:
            storage: {{ .Values.db.storage }}
    storageClassName: {{ .Values.storageClassName }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: media
spec:
    accessModes:
      - ReadWriteMany
    resources:
        requests:
            storage: {{ .Values.web.storage }}
    storageClassName: {{ .Values.storageClassName }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: redis
spec:
    accessModes:
      - ReadWriteOnce
    resources:
        requests:
            storage: {{ .Values.redis.storage }}
    storageClassName: {{ .Values.storageClassName }}