apiVersion: v1
kind: Service
metadata:
    name: db
    labels:
        {{- include "diov.db.labels" . | nindent 8 }}
spec:
    selector:
        {{- include "diov.db.selectorLabels" . | nindent 8 }}
    ports:
      - port: 1433
---
apiVersion: v1
kind: Service
metadata:
    name: redis
    labels:
        {{- include "diov.redis.labels" . | nindent 8 }}
spec:
    selector:
        {{- include "diov.redis.selectorLabels" . | nindent 8 }}
    ports:
      - port: 6379
---
apiVersion: v1
kind: Service
metadata:
    name: web
    labels:
        {{- include "diov.web.labels" . | nindent 8 }}
spec:
    selector:
        {{- include "diov.web.selectorLabels" . | nindent 8 }}
    ports:
      - name: http
        port: 80