apiVersion: v1
kind: Service
metadata:
    name: db
    labels:
        service: diov-db
spec:
    selector:
        service: diov-db
    ports:
      - port: 1433
---
apiVersion: v1
kind: Service
metadata:
    name: redis
    labels:
        service: diov-redis
spec:
    selector:
        service: diov-redis
    ports:
      - port: 6379
---
apiVersion: v1
kind: Service
metadata:
    name: web
    labels:
        service: diov-web
spec:
    selector:
        service: diov-web
    ports:
      - name: http
        port: 80