version: "3.8"
services:
    devcontainer:
        image: mcr.microsoft.com/devcontainers/dotnet:8.0-bookworm
        volumes:
          - ..:/workspace:cached
        command: sleep infinity
    mssql:
        image: mcr.microsoft.com/mssql/server:latest
        environment:
            ACCEPT_EULA: "Y"
            MSSQL_PID: "Express"
            SA_PASSWORD: "P@ssword123"
    redis:
        image: redis
