db:
    additionalVolumeMounts: []
    additionalVolumes: []
    image: mcr.microsoft.com/mssql/server:2019-latest
    persistence:
        enabled: false
        mountPath: /var/opt/mssql
        storage: 2Gi
        storageClassName:
    replicas: 1
    resources:
        limits:
            cpu: 1
            memory: 4Gi
        requests:
            cpu: 50m
            memory: 256Mi
    saPassword:

redis:
    additionalVolumeMounts: []
    additionalVolumes: []
    image: redis
    persistence:
        enabled: false
        mountPath: /data
        storage: 2Gi
        storageClassName:
    replicas: 1
    resources:
        limits:
            cpu: 1
            memory: 2Gi
        requests:
            cpu: 50m
            memory: 256Mi

web:
    additionalVolumeMounts: []
    additionalVolumes: []
    db:
        password:
        userId:
    externalIdentityProviders:
        google:
            adminAuthorization:
            clientId:
            clientSecret:
    host: example.com
    image: nulld3v/diov
    ingress:
        annotations: {}
    persistence:
        enabled: false
        mountPath: /app/wwwroot/media
        storage: 2Gi
        storageClassName:
    replicas: 1
    resources:
        limits:
            cpu: 2
            memory: 2Gi
        requests:
            cpu: 50m
            memory: 256Mi
    serilog:
        minimumLevel: Warning