db:
    additionalVolumeMounts: []
    additionalVolumes: []
    image: mcr.microsoft.com/mssql/server:2022-latest
    persistence:
        enabled: false
        mountPath: /var/opt/mssql
        storage: 2Gi
        storageClassName:
    replicas: 1
    resources:
        limits:
            cpu: 1
            memory: 4Gi
        requests:
            cpu: 25m
            memory: 1Gi
    saPassword:

redis:
    additionalVolumeMounts: []
    additionalVolumes: []
    image: redis
    persistence:
        enabled: false
        mountPath: /data
        storage: 2Gi
        storageClassName:
    replicas: 1
    resources:
        limits:
            cpu: 1
            memory: 2Gi
        requests:
            cpu: 10m
            memory: 32Mi

web:
    additionalVolumeMounts: []
    additionalVolumes: []
    db:
        password:
        userId:
    env:
      - name: ASPNETCORE_ENVIRONMENT
        value: Production
      - name: ExternalAuthentication__Google__AdminAuthorization
        value:
      - name: ExternalAuthentication__Google__ClientId
        value:
      - name: ExternalAuthentication__Google__ClientSecret
        value:
      - name: Serilog__MinimumLevel
        value: Warning
    host: example.com
    image: nulld3v/diov
    ingress:
        annotations: {}
    persistence:
        enabled: false
        mountPath: /app/wwwroot/media
        storage: 2Gi
        storageClassName:
    replicas: 1
    resources:
        limits:
            cpu: 2
            memory: 2Gi
        requests:
            cpu: 10m
            memory: 64Mi