name: Build .NET

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - name: Setup
            uses: actions/setup-dotnet@v4
            with:
                dotnet-version: 8
          - name: Build
            run: dotnet build -c Release
