name: Build

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@master
          - name: .NET Core
            uses: actions/setup-dotnet@v1
            with:
                dotnet-version: '3.1.102'
          - name: Build
            run: dotnet build -c Release Web/Diov.Web.csproj
