name: Publish release Docker image

on:
    release:
        types:
          - published

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
          - name: Version
            run: echo "VERSION=${GITHUB_REF:10}+${GITHUB_SHA::8}" >> $GITHUB_ENV
          - name: Login to DockerHub
            uses: docker/login-action@v2
            with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
          - name: Build and push
            id: docker_build
            uses: docker/build-push-action@v3
            with:
                push: true
                tags: nulld3v/diov:$VERSION